stack:
  densify:
    username: 'forwarder' # mandatory
    encrypted_password: 'v117e99fe4f74c299f9275106fcb890cb9ab0af38336a46c7e0372081525a76640d2a9d71b245c0b140155cfd4ffeba57c7a3a1f01d44f1ce84c8a54241efc2be9' # mandatory

container-optimization-data-forwarder:
  config:
    forwarder:
      densify:
        url:
          host: 'densifytest.densify.com' # mandatory: <instance>.densify.com
    clusters:
      - name: 'demo01' # mandatory

# The following section is optional, and is required only in two use-cases:
# 1. The persistent volume for Prometheus has to use an explicit storage class (not the default)
# 2. For future use: we may have additional exporters required such as NVIDIA's DCGM exporter, 
#    typically deployed using the GPU Operator (https://github.com/NVIDIA/gpu-operator) in its own namespace.
# In these two cases, uncomment the following section and the relevant sub-section/s:

# prometheus: # optional
  # server:
    # persistentVolume:
    #   storageClass: <changeme-storage-class>
    # namespaces:
    #   - <changeme-exporter-namespace>