apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  project: default

  source:
    repoURL: https://github.com/david-chase/argocd01.git
    targetRevision: HEAD
    path: tokyo/apps/cert-manager

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated: {}
