apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubex-automation-controller
  namespace: argocd
  labels:
    appversion: "v1.0.2"
spec:
  project: default
  source:
    repoURL: https://github.com/david-chase/argocd01
    targetRevision: HEAD
    path: kubex-automation-controller
    kustomize:
      enableHelm: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kubex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: cilium.io
      kind: CiliumIdentity
