# Create a namespace
apiVersion: v1
kind: Namespace
metadata:
  name: cuda-vector     # Enter namespace
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cuda-vector-cron
  namespace: cuda-vector
spec:
  schedule: "*/1 * * * *"  # Every minute
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: vectoradd
            image: nvidia/samples:vectoradd-cuda11.2
            command: ["bash", "-c"]
            args: ["/vectorAdd"]
            resources:
              limits:
                nvidia.com/gpu: 1