apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-storage
  namespace: argocd
  labels:
    appversion: "v0.0.31"
spec:
  project: default

  source:
    repoURL: https://github.com/david-chase/argocd01.git
    targetRevision: HEAD
    path: local-path-storage

  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage

  syncPolicy:
    automated: {}
