stack:
  densify:
    # 2025.06.09;16:49 Commenting out credentials in favour of external secret
    # username: 'forwarder' # mandatory
    # encrypted_password: '' # mandatory
    # END
container-optimization-data-forwarder:
  config:
    forwarder:
      densify:
        url:
          host: 'densifytest.densify.com' # mandatory: <instance>.densify.com
    clusters:
      - name: 'demo01' # mandatory
