apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: argocd-server
          resources:
            requests:
              cpu: "10m"
              memory: "60Mi"          
            limits:
              cpu: null
              memory: "410Mi"