apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubex-prometheus-server
  namespace: densify
spec:
  template:
    spec:
      containers:
        - name: prometheus-server
          resources:
            requests:
              cpu: "60m"
              memory: "2110Mi"          
            limits:
              memory: "4960Mi"