apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubex-automation-stack-kube-state-metrics
  namespace: densify
spec:
  template:
    spec:
      containers:
        - name: kube-state-metrics
          resources:
            requests:
              cpu: "10m"
              memory: "60Mi"
            limits:
              cpu: null
              memory: "160Mi"