apiVersion: apps/v1
kind: Daemonset
metadata:
  name: node-agent
  namespace: kubescape
spec:
  template:
    spec:
      containers:
        - name: node-agent
          resources:
            requests:
              cpu: "100m"
              memory: "180Mi"          
            limits:
              cpu: null
              memory: "1800Mi"