apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-agent
  namespace: kubescape
spec:
  template:
    spec:
      containers:
        - name: node-agent
          resources:
            limits:
              cpu: "500m"
              memory: "1800Mi"
            requests:
              cpu: "100m"
              memory: "250Mi"