apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: densify-api-secret
  namespace: densify
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: densify-api-secret       # ← the name of the resulting Kubernetes Secret
    creationPolicy: Owner
  data:
    - secretKey: username          # ← key in the K8s Secret
      remoteRef:
        key: densify-api-secret    # ← name of the AWS secret
        property: username         # ← property inside the AWS secret
    - secretKey: encrypted_password
      remoteRef:
        key: densify-api-secret
        property: encrypted_password