apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations: |
    cilium.io/v1/CiliumIdentity:
      ignoreDifferences: |
        jsonPointers:
          - /metadata/annotations
          - /metadata/labels
          - /metadata/managedFields
          - /metadata/resourceVersion
          - /metadata/uid
          - /metadata/creationTimestamp
          - /metadata/generation
          - /metadata/selfLink
    cilium.io/v2/CiliumIdentity:
      ignoreDifferences: |
        jsonPointers:
          - /metadata/annotations
          - /metadata/labels
          - /metadata/managedFields
          - /metadata/resourceVersion
          - /metadata/uid
          - /metadata/creationTimestamp
          - /metadata/generation
          - /metadata/selfLink