apiVersion: v1
kind: Service
metadata:
  name: coredns-external           # Name for the service
  namespace: kube-system
  annotations:
    description: "External service for MetalLB for coredns"
  labels:
    k8s-app: kube-dns
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.230   # Must be in MetalLB IP pool
  selector:
    k8s-app: kube-dns
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: dns
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: dns-tcp
  sessionAffinity: None
