apiVersion: v1
kind: Service
metadata:
  name: grafana-external           # Name for the service
  namespace: grafana
  annotations:
    description: "External service for MetalLB for Grafana"
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.0.0
    helm.sh/chart: grafana-9.0.1
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.233   # Must be in MetalLB IP pool
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  ports:
    - name: service
      protocol: TCP
      port: 80
      targetPort: 3000
  sessionAffinity: None
