apiVersion: v1
kind: Service
metadata:
  name: kubex-prometheus-server-external
  namespace: densify
  annotations:
    description: "External service for MetalLB for Prometheus"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: kubex-automation-stack
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/version: v3.1.0
    helm.sh/chart: prometheus-27.3.0
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.232
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: kubex-automation-stack
    app.kubernetes.io/name: prometheus
  ports:
    - name: http
      port: 80
      targetPort: 9090
      protocol: TCP
  sessionAffinity: None
