apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: efk-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.10.2
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "https://elasticsearch:9200"
        - name: ELASTICSEARCH_USERNAME
          value: "kibana_system"
        - name: ELASTICSEARCH_PASSWORD
          value: "pi_923oQEfSKZ0Mg2Q+H"
        - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
          value: "none"
        - name: XPACK_SECURITY_ENCRYPTIONKEY
          value: "qysl5yhl927dbchr62kl08xtehsyav3l"
        ports:
        - containerPort: 5601