apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-http-route
  namespace: argocd
spec:
  parentRefs:
  - name: tokyo-gateway
    namespace: gateway # Points to your specific gateway namespace
  hostnames:
  - "argocd.tokyo.home.arpa"
  - "argocd.tokyo.home"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: argocd-server
      port: 80