apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-creds
  namespace: grafana
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: grafana-creds       # ← the name of the resulting Kubernetes Secret
    creationPolicy: Owner
  data:
    - secretKey: admin-user          # ← key in the K8s Secret
      remoteRef:
        key: grafana-creds    # ← name of the AWS secret
        property: admin-user         # ← property inside the AWS secret
    - secretKey: admin-password
      remoteRef:
        key: grafana-creds
        property: admin-password