# Files I've injected into the Helm chart templates folder:
#  secret-store.yaml
#  external-secret.yaml 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets               # App name
  namespace: argocd
  labels:
    appversion: "v0.17.0"     # Version of the app 
spec:
  project: default
  source:
    repoURL: https://github.com/david-chase/argocd01
    targetRevision: HEAD
    path: external-secrets   # This folder should hold the Helm chart
    # helm:
      # valueFiles:
      #  - values.yaml               # This must exist in the chart folder in the Git repo
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets          # Namespace to deploy to
  syncPolicy:
    automated:
      prune: true
      selfHeal: true        # Auto-sync?
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: cilium.io
      kind: CiliumIdentity