apiVersion: v1
kind: Secret
metadata:
  name: awssm-secret
  namespace: external-secrets
type: Opaque
data:
  access-key: QUtJQVVFTDRJVTI1NFo3Q0YzQTY=
  secret-access-key: bHU3NWdCMVpmSTNHTER0Rk5CNDNTTVEreFlZRDlqTUhLRlk2ZkpWWQ==
