apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets            # Namespace to deploy to

resources:
  - secret-store.yaml                  # List of manifests to apply, if any
  - external-secret.yaml

helmCharts:
  - name: external-secrets             # Chart name from the repo
    repo:  https://charts.external-secrets.io           # URL of repo
    valuesFile: values-overlay.yaml    # ONLY the values we want to override
    version: 0.18.1                 # Chart version from the repo 