apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-external-secrets-webhook
spec:
  template:
    spec:
      volumes:
        - name: certs
          secret:
            secretName: release-name-external-secrets-webhook
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
              - key: ca.crt
                path: ca.crt
