certController:
  enabled: true

webhook:
  certManager:
    enabled: true
    create: true
    annotations:
      cert-manager.io/inject-ca-from: external-secrets/release-name-external-secrets-webhook
  cert:
    generate: true