# fullnameOverride: release-name-external-secrets
certController:
  create: true
  extraArgs:
    service-namespace: external-secrets
webhook:
  create: true
  certManager:
    enabled: false
    cert:
      create: true
      duration: "8760h"
  certMountPath: /tmp/certs
  certVolumeMounts:
    items:
      - key: tls.crt
        path: tls.crt
      - key: tls.key
        path: tls.key
      - key: ca.crt
        path: ca.crt

