namespace: external-secrets

certController:
  enabled: true
  service:
    name: release-name-external-secrets-webhook
    namespace: external-secrets
  secret:
    name: release-name-external-secrets-webhook
    namespace: external-secrets

webhook:
  create: true
  certManager:
    enabled: false
    cert:
      create: true
      duration: "8760h"