# fullnameOverride: release-name-external-secrets
certController:
  create: true
  extraArgs:
    service-namespace: external-secrets
webhook:
  create: true
  certManager:
    enabled: false
    cert:
      create: true
      duration: "8760h"
