namespace: external-secrets

certController:
  enabled: true

webhook:
  create: true
  certManager:
    enabled: false
    cert:
      create: true
      duration: "8760h"
    # annotations:
    #   cert-manager.io/inject-ca-from: external-secrets/release-name-external-secrets-webhook