apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: metallb-system

resources:
  - address-pool.yaml                   # Any additional manifests to apply
  - advertisement.yaml

helmCharts:
  - name: metallb               # App name
    repo: https://metallb.github.io/metallb
    # valuesFile: ../values.yaml        # ONLY the values we want to override
    version: 0.15.2                    # From Chart.yaml
    releaseName: metallb