apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - address-pool.yaml                   # Any additional manifests to apply
  - advertisement.yaml

helmCharts:
  - name: metallb               # App name
    path: ../charts/metallb       # Location of the chart
    # valuesFile: ../values.yaml        # ONLY the values we want to override
    version: 0.15.2                    # From Chart.yaml
    releaseName: metallb