---
apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-load-generator
  namespace: nginx-rollout
spec:
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      restartPolicy: Never
      containers:
      - name: load-generator
        image: williamyeh/hey:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting aggressive load generation for 60 seconds..."
          hey -z 60s -c 50 -q 10 http://nginx-rollout.nginx-rollout.svc.cluster.local:80/
          echo "Load generation complete"
  backoffLimit: 0
