---
apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-load-generator
  namespace: nginx-rollout
spec:
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      restartPolicy: Never
      containers:
      - name: load-generator
        image: alpine:latest
        command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache curl
          echo "Starting aggressive load generation for 120 seconds..."
          END_TIME=$(($(date +%s) + 120))
          while [ $(date +%s) -lt $END_TIME ]; do
            for i in $(seq 1 100); do
              curl -s http://nginx-rollout.nginx-rollout.svc.cluster.local:80/ > /dev/null &
            done
            sleep 0.1
          done
          wait
          echo "Load generation complete"
  backoffLimit: 0
