apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: efk-stack
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kube.*
      format json
    </source>

    <match kube.**>
      @type elasticsearch
      host elasticsearch
      port 9200
      logstash_format true
    </match>