apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-havana
  namespace: harbor
spec:
  secretName: harbor-tls
  duration: 262800h

  subject:
    organizations:
      - "Example"
  commonName: harbor.havana
  dnsNames:
    - harbor.havana
    - 192.168.1.100
    - localhost

  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer