apiVersion: v1
kind: Service
metadata:
  name: argocd-external           # Name for the service
  namespace: argocd
  annotations:
    description: "External service for MetalLB for Argo CD"
  labels:
    # Copy this section from internal service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.231   # Must be in MetalLB IP pool
  selector:
    # Copy this section from internal service
  ports:
    # Copy this section from internal service
  sessionAffinity: None
