apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        hosts {
          192.168.1.3	    miami
          192.168.1.4     obsidian
          192.168.1.100   havana
          192.168.1.5     dchaselt24
          192.168.1.230   dns.havana
          192.168.1.231   argocd.havana
          192.168.1.232   prometheus.havana
          192.168.1.233   grafana.havana
          192.168.1.234   kibana.havana
          fallthrough
        }
        
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus 0.0.0.0:9153
        forward . 1.1.1.1 8.8.8.8
        cache 30
        loop
        reload
        loadbalance
    }