apiVersion: v1
kind: Service
metadata:
  name: argocd-external           # Name for the service
  namespace: argocd
  annotations:
    description: "External service for MetalLB for Argo CD"
  labels:
    # Copy this section from internal service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.231   # Must be in MetalLB IP pool
  selector:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
  sessionAffinity: None
