apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd               # Namespace to deploy to

resources:
  - external-service.yaml       # List of manifests to apply, if any

helmCharts:
  - name: argo-cd               # Chart name from the repo
    repo: https://argoproj.github.io/argo-helm          # URL of repo
    valuesFile: values-overlay.yaml        # ONLY the values we want to override
    version: 8.1.2              # Chart version from the repo
    releaseName: argo-cd         