global:
  domain: argocd.havana
configs:
  cm:
    create: true
    kustomize.buildOptions: --enable-helm
    resource.customizations: |
      apps/Deployment:
        ignoreDifferences: |
          jqPathExpressions:
            - .spec.template.spec.containers[].resources.requests
            - .spec.template.spec.containers[].resources.limits
      apps/StatefulSet:
        ignoreDifferences: |
          jqPathExpressions:
            - .spec.template.spec.containers[].resources.requests
            - .spec.template.spec.containers[].resources.limits
      apps/DaemonSet:
        ignoreDifferences: |
          jqPathExpressions:
            - .spec.template.spec.containers[].resources.requests
            - .spec.template.spec.containers[].resources.limits
      admissionregistration.k8s.io/MutatingWebhookConfiguration:
        ignoreDifferences: |
          jsonPointers:
          - /webhooks/0/clientConfig/caBundle
      admissionregistration.k8s.io/ValidatingWebhookConfiguration:
        ignoreDifferences: |
          jsonPointers:
          - /webhooks/0/clientConfig/caBundle
      apiextensions.k8s.io/CustomResourceDefinition:
        ignoreDifferences: |
          jsonPointers:
          - /spec/conversion/webhook/clientConfig/caBundle 
  cmp:
    create: true
    plugins:
      kustomized-helm:
        init:
          command: ["/bin/sh", "-c"]
          args: ["helm dependency build || true"]
        generate:
          command: [ "sh", "-c" ]
          #args: ["echo \"$HELM_VALUES\" | helm template . --name-template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE $HELM_ARGS -f - > all.yaml && kustomize build"]
          args: ["helm template . --name-template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE $HELM_ARGS  > all.yaml && kustomize build"]   
  secret:
    
    # 2025.07.01 Create secret
    # Set createSecret to true to bootstrap Argo CD but set it to false for argocd to self-manage
    createSecret: false
    # END Create secret

    argocdServerAdminPassword: "$2a$12$d61E8ThJrrn0iao4OHyC6Or6SWA.T8JOmLVe9lGSsn1GFnrf9KIvu"