apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: argocd-tls
  commonName: 192.168.1.100
  dnsNames:
    - 192.168.1.100
    - havana
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  duration: 262800h # 3 years (use 87600h for 10 years, 262800h for 30)
  renewBefore: 720h # 30 days before expiration