apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator              # App name
  namespace: argocd
  labels:
    appversion: "v25.3.1"     # Version of the app 
spec:
  project: default
  source:
    repoURL: https://github.com/david-chase/argocd01
    targetRevision: HEAD
    path: gpu-operator             # This folder holds the kustomize.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator          # Namespace to deploy to
  syncPolicy:
    automated:
      prune: true
      selfHeal: true                # Auto-sync?
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - Replace=true  # <-- This helps with hook execution ordering
  ignoreDifferences:
    - group: cilium.io
      kind: CiliumIdentity