apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - ../charts/<chartname>             # Folder holding the chart
  - densify-api-secret.yaml           # Any additional manifests to apply
  - kubex-prometheus-server-external.yaml

helmCharts:
  - name: kubex-automation-stack               # App name
    path: ../charts/kubex-automation-stack       # Location of the chart
    valuesFile: ../values-overlay.yaml        # ONLY the values we want to override
    version: 0.9.6                    # From Chart.yaml
    releaseName: kubex-automation-stack