apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: <name>                      # Name the external secret
  namespace: <namespace>            # Namespace to place the external secret
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: <secretname>             # ← the name of the resulting Kubernetes Secret
    creationPolicy: Owner
  data:
    - secretKey: <key1>            # ← key in the K8s Secret
      remoteRef:
        key: <secretname>          # ← name of the AWS secret
        property: <key1>           # ← property inside the AWS secret
    - secretKey: <key2>
      remoteRef:
        key: <secretname>
        property: <key2>