apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <name of app>               # App name
  namespace: argocd
  labels:
    appversion: "<app version>"     # Version of the app 
spec:
  project: default
  source:
    repoURL: https://github.com/david-chase/argocd01.git
    targetRevision: HEAD
    path: tokyo/apps/<app folder>   # Location where the manifests are stored
  destination:
    server: https://kubernetes.default.svc
    namespace: <namespace>          # Namespace to deploy to
  syncPolicy:
    automated:
      prune: true
      selfHeal: true                # Auto-sync?