apiVersion: v1
kind: Secret
metadata:
  name: densify-api-secret
  namespace: densify-automation
type: Opaque
data:
  DENSIFY_USERNAME: ZGNoYXNlQGRlbnNpZnkuY29t
  DENSIFY_PASSWORD: d0M4XnBvWkpOVkoxZXc4VQ==