apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: efk-stack
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
        volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: dockercontainerlogdirectory
          mountPath: /var/log/containers
        - name: default-token
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: fluentd-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: dockercontainerlogdirectory
        hostPath:
          path: /var/log/containers
      - name: default-token
        projected:
          sources:
            - serviceAccountToken:
                path: token
                expirationSeconds: 3600
                audience: api