apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:                  # These are examples
  - namespace.yaml
  - elasticsearch-deployment.yaml
  - elasticsearch-service.yaml
  - kibana-deployment.yaml
  - kibana-service.yaml
  - fluentd-configmap.yaml
  - fluentd-daemonset.yaml