apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubex-automation-stack               # App name
  namespace: argocd
  labels:
    appversion: "4.2.2"     # Version of the app 
spec:
  project: default
  source:
    repoURL: https://github.com/david-chase/argocd01
    targetRevision: HEAD
    path: kubex-automation-stack/manifests    # This folder holds the kustomize.yaml
    kustomize:
      buildOptions: --enable-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: densify          # Namespace to deploy to
  syncPolicy:
    automated:
      prune: true
      selfHeal: true                # Auto-sync?
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: cilium.io
      kind: CiliumIdentity