apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: <namespace>                 # Namespace to deploy to

resources:
  # - address-pool.yaml                  # List of manifests to apply, if any

helmCharts:
  - name: kubex-automation-stack                # Chart name from the repo
    repo: https://densify-dev.github.io/helm-charts           # URL of repo
    valuesFile: values-overlay.yaml    # ONLY the values we want to override
    version: 0.9.10                # Chart version from the repo 