stack:
  densify:
    createSecret: false
    # 2025.06.09;16:49 Commenting out credentials in favour of external secret
    # username: 'forwarder' # mandatory
    # encrypted_password: '' # mandatory
    # END
  
container-optimization-data-forwarder:
  config:
    forwarder:
      densify:
        url:
          host: 'densifytest.densify.com' # mandatory: <instance>.densify.com
    clusters:
      - name: 'demo01' # mandatory
prometheus:
  alertmanager:
    enabled: true 
  prometheus-pushgateway:
    enabled: true
  server:
    persistentVolume:
      size: 10Gi
    retention: "7d"
    retentionSize: "8GiB"