# Files I've injected into the Helm chart templates folder:
#  address-pool.yaml
#  advertisement.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb               # App name
  namespace: argocd
  labels:
    appversion: "0.14.9"     # Version of the app 
spec:
  project: default
  source:
    repoURL: https://github.com/david-chase/argocd01
    targetRevision: HEAD
    path: tokyo/apps/metallb   # This folder should hold the Helm chart
    helm:
#      parameters:
#      - name: crds.enabled
#        value: "true"
#      valueFiles:
#        - values.yaml               # This must exist in the chart folder in the Git repo
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system         # Namespace to deploy to
  syncPolicy:
    automated:
      prune: true
      selfHeal: true                # Auto-sync?
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: cilium.io
      kind: CiliumIdentity
