apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx               # App name
  namespace: argocd
  labels:
    appversion: "1.12.2"     # Version of the app 
spec:
  project: default
  source:
    repoURL: https://github.com/david-chase/argocd01
    targetRevision: HEAD
    path: tokyo/apps/ingress-nginx   # This folder should hold the Helm chart
    helm:
      parameters:
      - name: controller.publishService.enabled
        value: "false"
      - name: hostPort.enabled
        value: "true"
      - name: hostPort.http
        value: "80"
      - name: controller.hostPort.https
        value: "443"
      - name: controller.kind
        value: "DaemonSet"
      - name: controller.service.type
        value: "ClusterIP"
#      valueFiles:
#        - values.yaml               # This must exist in the chart folder in the Git repo
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx          # Namespace to deploy to
  syncPolicy:
    automated:
      prune: true
      selfHeal: true                # Auto-sync?
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: cilium.io
      kind: CiliumIdentity
