apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx-ingresses               # App name
  namespace: argocd
  labels:
    appversion: "0.1.0"     # Version of the app 
spec:
  project: default
  source:
    repoURL: https://github.com/david-chase/argocd01.git
    targetRevision: HEAD
    path: tokyo/apps/my-nginx-ingresses   # Location where the manifests are stored
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx         # Namespace to deploy to
  syncPolicy:
    automated:
      prune: true
      selfHeal: true                # Auto-sync?