apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'harbor'                    # App name
  namespace: argocd
  labels:
    appversion: "2.13.1"            # Version of the app
spec:
  project: default
  source:
    repoURL: 'https://github.com/david-chase/argocd01'
    path: tokyo/apps/harbor         # Location where the subapps are
    directory:
      recurse: true                 # This enables app-of-apps
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: harbor               # Namespace to deploy to
  syncPolicy:
    automated:                      # Auto-sync
      prune: true                   # Prunes no longer used resources
      selfHeal: true                # This enables self-heal
