apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack              # App name
  namespace: argocd
  labels:
    appversion: "0.82.2"     # Version of the app 
spec:
  project: default
  source:
    repoURL: https://github.com/david-chase/argocd01
    targetRevision: HEAD
    path: tokyo/apps/kube-prometheus-stack   # This folder should hold the Helm chart
    helm:
#      parameters:
#      - name: crds.enabled
#        value: "true"
      valueFiles:
        - values.yaml               # This must exist in the chart folder in the Git repo
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring          # Namespace to deploy to
  syncPolicy:
    automated:
      prune: true
      selfHeal: true                # Auto-sync?
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: cilium.io
      kind: CiliumIdentity
