---
# Source: container-optimization-data-forwarder/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: forwarder-densify-forwarder
  namespace: densify
  labels:
    app: densify-forwarder
    chart: container-optimization-data-forwarder-4.0.3
    release: forwarder
    heritage: Helm
data:
  config.yaml : |
    forwarder:
      densify:
        url:
          host: densifytest.densify.com
    prometheus:
      url:
        host: kubex-prometheus-server
        port: 80
    clusters:
      - name: "<cluster-1 name>"
        identifiers:
          <label name>: "<label value>"
      - name: "<cluster-2 name>"
        identifiers:
          <label name>: "<label value>"
---
# Source: container-optimization-data-forwarder/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: forwarder-densify-forwarder
  namespace: densify
  labels:
    app: densify-forwarder
    chart: container-optimization-data-forwarder-4.0.3
    release: forwarder
    heritage: Helm
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: densify-forwarder
        release: forwarder
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
    # ================================
    # Add an image pull secret for ECR
    # ================================
      imagePullSecrets:
        - name: ecr-creds
      initContainers:
      containers:
        - name: densify-forwarder
          image: "284265326267.dkr.ecr.ca-central-1.amazonaws.com/tokyo:densify-421"
          imagePullPolicy: Always
          env:
            - name: CONFIG_TYPE
              value: "yaml"
          volumeMounts:
          - name: config
            mountPath: /config
      volumes:
        - name: config
          configMap:
            name: forwarder-densify-forwarder
            items:
            - key: config.yaml
              path: config.yaml
      restartPolicy: Never
---
# Source: container-optimization-data-forwarder/templates/cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: forwarder-densify-forwarder
  namespace: densify
  labels:
    app: densify-forwarder
    chart: container-optimization-data-forwarder-4.0.3
    release: forwarder
    heritage: Helm
spec:
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: densify-forwarder
            release: forwarder
        spec:
          nodeSelector:
            kubernetes.io/os: linux
            kubernetes.io/arch: amd64
          containers:
          - name: densify-forwarder
            image: "284265326267.dkr.ecr.ca-central-1.amazonaws.com/tokyo:densify-421"
            imagePullPolicy: Always
            env:
              - name: CONFIG_TYPE
                value: "yaml"
            volumeMounts:
            - name: config
              mountPath: /config
          volumes:
            - name: config
              configMap:
                name: forwarder-densify-forwarder
                items:
                - key: config.yaml
                  path: config.yaml
          restartPolicy: Never
