apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Argo CD
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:david-chase/argocd01.git'
    path: apps
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
