apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grove-system-0.1.0-alpha.3
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/david-chase/argocd01
    targetRevision: HEAD
    path: grove-system-0.1.0-alpha.3

  destination:
    server: https://kubernetes.default.svc
    namespace: grove-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

