apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspect
  namespace: densify-automation
spec:
  containers:
  - name: inspector
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: target-volume
      mountPath: /mnt
  volumes:
  - name: target-volume
    persistentVolumeClaim:
      claimName: densify-recommendations-pvc
  restartPolicy: Never